# Generated by Django 3.2 on 2021-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdcData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edc_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='EDC Value')),
            ],
        ),
    ]
