# Generated by Django 3.2 on 2021-04-14 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcdata',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Published Date'),
            preserve_default=False,
        ),
    ]
