# Generated by Django 3.2 on 2021-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0002_edcdata_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcdata',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Published Date'),
        ),
    ]
