# Generated by Django 3.2 on 2021-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0003_alter_edcdata_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcdata',
            name='edc_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='EDC Value'),
        ),
    ]
