# Generated by Django 3.2 on 2021-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politics', models.TextField(verbose_name='p')),
                ('economics', models.TextField(verbose_name='e')),
                ('socials', models.TextField(verbose_name='s')),
                ('technologies', models.TextField(verbose_name='t')),
            ],
        ),
        migrations.CreateModel(
            name='Swot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField(verbose_name='s')),
                ('weaknesses', models.TextField(verbose_name='w')),
                ('opotunities', models.TextField(verbose_name='o')),
                ('threads', models.TextField(verbose_name='t')),
            ],
        ),
    ]
