# Generated by Django 3.2 on 2021-05-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PestAndSwot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economics', models.TextField(verbose_name='e')),
                ('description', models.TextField(verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunities', models.TextField(verbose_name='o')),
                ('description', models.TextField(verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Politic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politics', models.TextField(verbose_name='p')),
                ('description', models.TextField(verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socials', models.TextField(verbose_name='s')),
                ('description', models.TextField(verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField(verbose_name='s')),
                ('description', models.TextField(verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologies', models.TextField(verbose_name='t')),
                ('description', models.TextField(verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threads', models.TextField(verbose_name='t')),
                ('description', models.TextField(verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaknesses', models.TextField(verbose_name='w')),
                ('description', models.TextField(verbose_name='remarks')),
            ],
        ),
        migrations.DeleteModel(
            name='Pest',
        ),
        migrations.DeleteModel(
            name='Swot',
        ),
    ]
