# Generated by Django 3.2 on 2021-05-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PestAndSwot', '0002_auto_20210514_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politic',
            name='description',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
    ]
