# Generated by Django 3.2 on 2021-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PestAndSwot', '0003_alter_politic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic',
            name='economics',
            field=models.TextField(blank=True, verbose_name='e'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='social',
            name='description',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='strength',
            name='description',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='weakness',
            name='description',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
    ]
