# Generated by Django 3.2 on 2021-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PestAndSwot', '0004_auto_20210514_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic',
            name='description',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='economic',
            name='economics',
            field=models.TextField(verbose_name='e'),
        ),
    ]
