# Generated by Django 3.2 on 2021-04-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Longitude')),
            ],
        ),
    ]
