# Generated by Django 3.2 on 2021-04-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20210416_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='device_name',
            field=models.TextField(blank=True, verbose_name='Device Name'),
        ),
    ]
