# Generated by Django 3.2 on 2021-05-16 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('emp_role', models.CharField(max_length=50, verbose_name='Role')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_status.zonecategory')),
            ],
        ),
    ]
